sudo: false

language: go

go:
 - 1.7
 - release

before_install:
 - go get github.com/mattn/goveralls

script:
 - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email:
    on_success: never
    on_failure: always
